
class Autogenerated {
  Data? data;
  bool? success;
  String? message;
  int? statusCode;

  Autogenerated({this.data, this.success, this.message, this.statusCode});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    success = json['success'];
    message = json['message'];
    statusCode = json['statusCode'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['success'] = this.success;
    data['message'] = this.message;
    data['statusCode'] = this.statusCode;
    return data;
  }
}

class Data {
  int? id;
  int? houseWorkerId;
  int? orderId;
  int? rating;
  HouseWorker? houseWorker;
  Order? order;

  Data(
      {this.id,
        this.houseWorkerId,
        this.orderId,
        this.rating,
        this.houseWorker,
        this.order});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    houseWorkerId = json['houseWorkerId'];
    orderId = json['orderId'];
    rating = json['rating'];
    houseWorker = json['houseWorker'] != null
        ? new HouseWorker.fromJson(json['houseWorker'])
        : null;
    order = json['order'] != null ? new Order.fromJson(json['order']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['houseWorkerId'] = this.houseWorkerId;
    data['orderId'] = this.orderId;
    data['rating'] = this.rating;
    if (this.houseWorker != null) {
      data['houseWorker'] = this.houseWorker!.toJson();
    }
    if (this.order != null) {
      data['order'] = this.order!.toJson();
    }
    return data;
  }
}

class HouseWorker {
  int? id;
  String? name;
  String? phone;
  String? dateOfBirth;
  String? email;
  String? linkFacebook;
  String? avatar;
  int? active;
  int? areaId;
  int? managerId;
  Manager? manager;
  List<String>? workerInOrders;
  List<WorkerTags>? workerTags;

  HouseWorker(
      {this.id,
        this.name,
        this.phone,
        this.dateOfBirth,
        this.email,
        this.linkFacebook,
        this.avatar,
        this.active,
        this.areaId,
        this.managerId,
        this.manager,
        this.workerInOrders,
        this.workerTags});

  HouseWorker.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    phone = json['phone'];
    dateOfBirth = json['dateOfBirth'];
    email = json['email'];
    linkFacebook = json['linkFacebook'];
    avatar = json['avatar'];
    active = json['active'];
    areaId = json['areaId'];
    managerId = json['managerId'];
    manager =
    json['manager'] != null ? new Manager.fromJson(json['manager']) : null;
    workerInOrders = json['workerInOrders'].cast<String>();
    if (json['workerTags'] != null) {
      workerTags = <WorkerTags>[];
      json['workerTags'].forEach((v) {
        workerTags!.add(new WorkerTags.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['phone'] = this.phone;
    data['dateOfBirth'] = this.dateOfBirth;
    data['email'] = this.email;
    data['linkFacebook'] = this.linkFacebook;
    data['avatar'] = this.avatar;
    data['active'] = this.active;
    data['areaId'] = this.areaId;
    data['managerId'] = this.managerId;
    if (this.manager != null) {
      data['manager'] = this.manager!.toJson();
    }
    data['workerInOrders'] = this.workerInOrders;
    if (this.workerTags != null) {
      data['workerTags'] = this.workerTags!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Manager {
  int? id;
  String? name;
  String? phone;
  String? dateOfBirth;
  String? email;
  String? linkFacebook;
  String? avatar;
  bool? active;
  int? roleId;
  Role? role;
  List<String>? houseWorkers;

  Manager(
      {this.id,
        this.name,
        this.phone,
        this.dateOfBirth,
        this.email,
        this.linkFacebook,
        this.avatar,
        this.active,
        this.roleId,
        this.role,
        this.houseWorkers});

  Manager.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    phone = json['phone'];
    dateOfBirth = json['dateOfBirth'];
    email = json['email'];
    linkFacebook = json['linkFacebook'];
    avatar = json['avatar'];
    active = json['active'];
    roleId = json['roleId'];
    role = json['role'] != null ? new Role.fromJson(json['role']) : null;
    houseWorkers = json['houseWorkers'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['phone'] = this.phone;
    data['dateOfBirth'] = this.dateOfBirth;
    data['email'] = this.email;
    data['linkFacebook'] = this.linkFacebook;
    data['avatar'] = this.avatar;
    data['active'] = this.active;
    data['roleId'] = this.roleId;
    if (this.role != null) {
      data['role'] = this.role!.toJson();
    }
    data['houseWorkers'] = this.houseWorkers;
    return data;
  }
}

class Role {
  int? id;
  String? name;
  List<String>? adminManagers;

  Role({this.id, this.name, this.adminManagers});

  Role.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    adminManagers = json['adminManagers'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['adminManagers'] = this.adminManagers;
    return data;
  }
}

class WorkerTags {
  int? id;
  String? name;
  int? houseWorkerId;
  String? houseWorker;

  WorkerTags({this.id, this.name, this.houseWorkerId, this.houseWorker});

  WorkerTags.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    houseWorkerId = json['houseWorkerId'];
    houseWorker = json['houseWorker'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['houseWorkerId'] = this.houseWorkerId;
    data['houseWorker'] = this.houseWorker;
    return data;
  }
}

class Order {
  int? id;
  String? endTime;
  String? dateTime;
  double? subTotal;
  double? total;
  int? houseId;
  int? packageId;
  int? promotionId;
  int? paymentMethodId;
  int? orderState;
  House? house;
  Package? package;
  PaymentMethod? paymentMethod;
  Promotion? promotion;
  List<OrderDetails>? orderDetails;
  List<String>? workerInOrders;

  Order(
      {this.id,
        this.endTime,
        this.dateTime,
        this.subTotal,
        this.total,
        this.houseId,
        this.packageId,
        this.promotionId,
        this.paymentMethodId,
        this.orderState,
        this.house,
        this.package,
        this.paymentMethod,
        this.promotion,
        this.orderDetails,
        this.workerInOrders});

  Order.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    endTime = json['endTime'];
    dateTime = json['dateTime'];
    subTotal = json['subTotal'];
    total = json['total'];
    houseId = json['houseId'];
    packageId = json['packageId'];
    promotionId = json['promotionId'];
    paymentMethodId = json['paymentMethodId'];
    orderState = json['orderState'];
    house = json['house'] != null ? new House.fromJson(json['house']) : null;
    package =
    json['package'] != null ? new Package.fromJson(json['package']) : null;
    paymentMethod = json['paymentMethod'] != null
        ? new PaymentMethod.fromJson(json['paymentMethod'])
        : null;
    promotion = json['promotion'] != null
        ? new Promotion.fromJson(json['promotion'])
        : null;
    if (json['orderDetails'] != null) {
      orderDetails = <OrderDetails>[];
      json['orderDetails'].forEach((v) {
        orderDetails!.add(new OrderDetails.fromJson(v));
      });
    }
    workerInOrders = json['workerInOrders'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['endTime'] = this.endTime;
    data['dateTime'] = this.dateTime;
    data['subTotal'] = this.subTotal;
    data['total'] = this.total;
    data['houseId'] = this.houseId;
    data['packageId'] = this.packageId;
    data['promotionId'] = this.promotionId;
    data['paymentMethodId'] = this.paymentMethodId;
    data['orderState'] = this.orderState;
    if (this.house != null) {
      data['house'] = this.house!.toJson();
    }
    if (this.package != null) {
      data['package'] = this.package!.toJson();
    }
    if (this.paymentMethod != null) {
      data['paymentMethod'] = this.paymentMethod!.toJson();
    }
    if (this.promotion != null) {
      data['promotion'] = this.promotion!.toJson();
    }
    if (this.orderDetails != null) {
      data['orderDetails'] = this.orderDetails!.map((v) => v.toJson()).toList();
    }
    data['workerInOrders'] = this.workerInOrders;
    return data;
  }
}

class House {
  int? id;
  String? number;
  bool? active;
  int? customerId;
  int? buildingId;
  Building? building;
  Customer? customer;
  List<String>? orders;

  House(
      {this.id,
        this.number,
        this.active,
        this.customerId,
        this.buildingId,
        this.building,
        this.customer,
        this.orders});

  House.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    number = json['number'];
    active = json['active'];
    customerId = json['customerId'];
    buildingId = json['buildingId'];
    building = json['building'] != null
        ? new Building.fromJson(json['building'])
        : null;
    customer = json['customer'] != null
        ? new Customer.fromJson(json['customer'])
        : null;
    orders = json['orders'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['number'] = this.number;
    data['active'] = this.active;
    data['customerId'] = this.customerId;
    data['buildingId'] = this.buildingId;
    if (this.building != null) {
      data['building'] = this.building!.toJson();
    }
    if (this.customer != null) {
      data['customer'] = this.customer!.toJson();
    }
    data['orders'] = this.orders;
    return data;
  }
}

class Building {
  int? id;
  String? name;
  bool? active;
  int? areaId;
  Area? area;
  List<String>? houses;

  Building(
      {this.id, this.name, this.active, this.areaId, this.area, this.houses});

  Building.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    active = json['active'];
    areaId = json['areaId'];
    area = json['area'] != null ? new Area.fromJson(json['area']) : null;
    houses = json['houses'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['active'] = this.active;
    data['areaId'] = this.areaId;
    if (this.area != null) {
      data['area'] = this.area!.toJson();
    }
    data['houses'] = this.houses;
    return data;
  }
}

class Area {
  int? id;
  String? name;
  bool? active;
  String? district;
  String? city;
  List<String>? buildings;

  Area(
      {this.id,
        this.name,
        this.active,
        this.district,
        this.city,
        this.buildings});

  Area.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    active = json['active'];
    district = json['district'];
    city = json['city'];
    buildings = json['buildings'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['active'] = this.active;
    data['district'] = this.district;
    data['city'] = this.city;
    data['buildings'] = this.buildings;
    return data;
  }
}

class Customer {
  int? id;
  String? name;
  String? phone;
  String? dateOfBirth;
  String? email;
  String? linkFacebook;
  String? avatar;
  int? eWallet;
  bool? active;
  List<CustomerPromotions>? customerPromotions;
  List<String>? houses;

  Customer(
      {this.id,
        this.name,
        this.phone,
        this.dateOfBirth,
        this.email,
        this.linkFacebook,
        this.avatar,
        this.eWallet,
        this.active,
        this.customerPromotions,
        this.houses});

  Customer.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    phone = json['phone'];
    dateOfBirth = json['dateOfBirth'];
    email = json['email'];
    linkFacebook = json['linkFacebook'];
    avatar = json['avatar'];
    eWallet = json['eWallet'];
    active = json['active'];
    if (json['customerPromotions'] != null) {
      customerPromotions = <CustomerPromotions>[];
      json['customerPromotions'].forEach((v) {
        customerPromotions!.add(new CustomerPromotions.fromJson(v));
      });
    }
    houses = json['houses'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['phone'] = this.phone;
    data['dateOfBirth'] = this.dateOfBirth;
    data['email'] = this.email;
    data['linkFacebook'] = this.linkFacebook;
    data['avatar'] = this.avatar;
    data['eWallet'] = this.eWallet;
    data['active'] = this.active;
    if (this.customerPromotions != null) {
      data['customerPromotions'] =
          this.customerPromotions!.map((v) => v.toJson()).toList();
    }
    data['houses'] = this.houses;
    return data;
  }
}

class CustomerPromotions {
  int? id;
  bool? isUsed;
  int? customerId;
  int? promotionId;
  String? customer;
  String? promotion;

  CustomerPromotions(
      {this.id,
        this.isUsed,
        this.customerId,
        this.promotionId,
        this.customer,
        this.promotion});

  CustomerPromotions.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    isUsed = json['isUsed'];
    customerId = json['customerId'];
    promotionId = json['promotionId'];
    customer = json['customer'];
    promotion = json['promotion'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['isUsed'] = this.isUsed;
    data['customerId'] = this.customerId;
    data['promotionId'] = this.promotionId;
    data['customer'] = this.customer;
    data['promotion'] = this.promotion;
    return data;
  }
}

class Package {
  int? id;
  String? name;
  int? duration;
  int? active;
  int? serviceId;
  double? price;
  Service? service;
  List<String>? orders;

  Package(
      {this.id,
        this.name,
        this.duration,
        this.active,
        this.serviceId,
        this.price,
        this.service,
        this.orders});

  Package.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    duration = json['duration'];
    active = json['active'];
    serviceId = json['serviceId'];
    price = json['price'];
    service =
    json['service'] != null ? new Service.fromJson(json['service']) : null;
    orders = json['orders'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['duration'] = this.duration;
    data['active'] = this.active;
    data['serviceId'] = this.serviceId;
    data['price'] = this.price;
    if (this.service != null) {
      data['service'] = this.service!.toJson();
    }
    data['orders'] = this.orders;
    return data;
  }
}

class Service {
  int? id;
  String? name;
  String? description;
  int? active;
  List<ExtraServices>? extraServices;
  List<String>? packages;

  Service(
      {this.id,
        this.name,
        this.description,
        this.active,
        this.extraServices,
        this.packages});

  Service.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    description = json['description'];
    active = json['active'];
    if (json['extraServices'] != null) {
      extraServices = <ExtraServices>[];
      json['extraServices'].forEach((v) {
        extraServices!.add(new ExtraServices.fromJson(v));
      });
    }
    packages = json['packages'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['description'] = this.description;
    data['active'] = this.active;
    if (this.extraServices != null) {
      data['extraServices'] =
          this.extraServices!.map((v) => v.toJson()).toList();
    }
    data['packages'] = this.packages;
    return data;
  }
}

class ExtraServices {
  int? id;
  String? name;
  String? description;
  int? price;
  int? active;
  int? serviceId;
  String? service;
  List<String>? orderDetails;

  ExtraServices(
      {this.id,
        this.name,
        this.description,
        this.price,
        this.active,
        this.serviceId,
        this.service,
        this.orderDetails});

  ExtraServices.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    description = json['description'];
    price = json['price'];
    active = json['active'];
    serviceId = json['serviceId'];
    service = json['service'];
    orderDetails = json['orderDetails'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['description'] = this.description;
    data['price'] = this.price;
    data['active'] = this.active;
    data['serviceId'] = this.serviceId;
    data['service'] = this.service;
    data['orderDetails'] = this.orderDetails;
    return data;
  }
}

class PaymentMethod {
  int? id;
  String? name;
  bool? active;
  List<String>? orders;

  PaymentMethod({this.id, this.name, this.active, this.orders});

  PaymentMethod.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    active = json['active'];
    orders = json['orders'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['active'] = this.active;
    data['orders'] = this.orders;
    return data;
  }
}

class Promotion {
  int? id;
  String? code;
  String? description;
  double? value;
  double? discount;
  int? amount;
  String? startDate;
  String? endDate;
  bool? active;
  String? image;
  List<CustomerPromotions>? customerPromotions;
  List<String>? orders;

  Promotion(
      {this.id,
        this.code,
        this.description,
        this.value,
        this.discount,
        this.amount,
        this.startDate,
        this.endDate,
        this.active,
        this.image,
        this.customerPromotions,
        this.orders});

  Promotion.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    code = json['code'];
    description = json['description'];
    value = json['value'];
    discount = json['discount'];
    amount = json['amount'];
    startDate = json['startDate'];
    endDate = json['endDate'];
    active = json['active'];
    image = json['image'];
    if (json['customerPromotions'] != null) {
      customerPromotions = <CustomerPromotions>[];
      json['customerPromotions'].forEach((v) {
        customerPromotions!.add(new CustomerPromotions.fromJson(v));
      });
    }
    orders = json['orders'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['code'] = this.code;
    data['description'] = this.description;
    data['value'] = this.value;
    data['discount'] = this.discount;
    data['amount'] = this.amount;
    data['startDate'] = this.startDate;
    data['endDate'] = this.endDate;
    data['active'] = this.active;
    data['image'] = this.image;
    if (this.customerPromotions != null) {
      data['customerPromotions'] =
          this.customerPromotions!.map((v) => v.toJson()).toList();
    }
    data['orders'] = this.orders;
    return data;
  }
}

class OrderDetails {
  int? id;
  int? extraServiceId;
  int? orderId;
  ExtraServices? extraService;
  String? order;

  OrderDetails(
      {this.id,
        this.extraServiceId,
        this.orderId,
        this.extraService,
        this.order});

  OrderDetails.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    extraServiceId = json['extraServiceId'];
    orderId = json['orderId'];
    extraService = json['extraService'] != null
        ? new ExtraServices.fromJson(json['extraService'])
        : null;
    order = json['order'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['extraServiceId'] = this.extraServiceId;
    data['orderId'] = this.orderId;
    if (this.extraService != null) {
      data['extraService'] = this.extraService!.toJson();
    }
    data['order'] = this.order;
    return data;
  }
}


